from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


# ============================================================
# CONSTRUCTAI PDF REPORT GENERATOR
# ============================================================

def generate_pdf_report(
    summary,
    results,
    recommendations,
):
    """
    Generate a professional Construction-AI
    Risk Intelligence PDF report.

    Parameters
    ----------
    summary : dict
        Executive risk summary.

    results : dict
        Complete output from main.run_analysis().

    recommendations : list
        Recommendations generated by recommendations.py.

    Returns
    -------
    BytesIO
        Generated PDF file.
    """

    # ========================================================
    # PDF BUFFER
    # ========================================================

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="ConstructAI Risk Intelligence Report",
        author="ConstructAI",
    )


    # ========================================================
    # STYLES
    # ========================================================

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ConstructAITitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=22,
        leading=27,
        spaceAfter=8,
    )

    subtitle_style = ParagraphStyle(
        "ConstructAISubtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=10,
        leading=14,
        spaceAfter=20,
    )

    heading_style = ParagraphStyle(
        "ConstructAIHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=19,
        spaceBefore=12,
        spaceAfter=8,
    )

    small_style = ParagraphStyle(
        "ConstructAISmall",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
    )

    normal_style = ParagraphStyle(
        "ConstructAINormal",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
    )


    # ========================================================
    # EXTRACT RESULTS
    # ========================================================

    project_risk = results.get(
        "project_risk",
        "Unknown",
    )

    equipment_mttf = results.get(
        "equipment_mttf",
        "N/A",
    )

    weather = results.get(
        "weather_prediction",
        results.get(
            "weather",
            "Unknown",
        ),
    )

    safety_report = results.get(
        "safety_report",
        {},
    )

    worker_report = results.get(
        "worker_protection_report",
        {},
    )

    site_report = results.get(
        "site_report",
        {},
    )

    compliance_report = results.get(
        "compliance_report",
        {},
    )

    insurance_report = results.get(
        "insurance_report",
        {},
    )


    # ========================================================
    # RISK VALUES
    # ========================================================

    site_risk_score = site_report.get(
        "site_risk_score",
        0,
    )

    safety_protection_score = worker_report.get(
        "safety_score",
        100,
    )

    try:
        safety_protection_score = float(
            safety_protection_score
        )
    except (
        TypeError,
        ValueError,
    ):
        safety_protection_score = 100

    safety_risk_score = max(
        0,
        min(
            100,
            100 - safety_protection_score,
        ),
    )

    insurance_score = insurance_report.get(
        "insurance_risk_score",
        0,
    )

    try:
        insurance_score = float(
            insurance_score
        )
    except (
        TypeError,
        ValueError,
    ):
        insurance_score = 0


    # ========================================================
    # OVERALL RISK
    # ========================================================

    risk_scores = [
        float(site_risk_score),
        float(safety_risk_score),
        float(insurance_score),
    ]

    overall_score = round(
        sum(risk_scores) / len(risk_scores)
    )

    if overall_score >= 70:
        overall_level = "High"
    elif overall_score >= 40:
        overall_level = "Medium"
    else:
        overall_level = "Low"


    # ========================================================
    # STORY / FLOW
    # ========================================================

    story = []


    # ========================================================
    # COVER
    # ========================================================

    story.append(
        Paragraph(
            "CONSTRUCTAI",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "Construction Risk Intelligence Report",
            subtitle_style,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    cover_data = [
        [
            Paragraph(
                "<b>Overall Risk</b>",
                normal_style,
            ),
            Paragraph(
                f"<b>{overall_level}</b>",
                normal_style,
            ),
        ],
        [
            Paragraph(
                "<b>Overall Risk Score</b>",
                normal_style,
            ),
            Paragraph(
                f"{overall_score}/100",
                normal_style,
            ),
        ],
        [
            Paragraph(
                "<b>Project Risk</b>",
                normal_style,
            ),
            Paragraph(
                str(project_risk),
                normal_style,
            ),
        ],
        [
            Paragraph(
                "<b>Weather</b>",
                normal_style,
            ),
            Paragraph(
                str(weather),
                normal_style,
            ),
        ],
        [
            Paragraph(
                "<b>Compliance</b>",
                normal_style,
            ),
            Paragraph(
                str(
                    compliance_report.get(
                        "compliance_status",
                        "Unknown",
                    )
                ),
                normal_style,
            ),
        ],
        [
            Paragraph(
                "<b>Insurance Risk</b>",
                normal_style,
            ),
            Paragraph(
                str(
                    insurance_report.get(
                        "insurance_risk_level",
                        "Unknown",
                    )
                ),
                normal_style,
            ),
        ],
    ]

    cover_table = Table(
        cover_data,
        colWidths=[
            65 * mm,
            95 * mm,
        ],
    )

    cover_table.setStyle(
        TableStyle(
            [
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey,
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(
        cover_table
    )

    story.append(
        Spacer(
            1,
            20,
        )
    )

    story.append(
        Paragraph(
            "Generated by the ConstructAI Agentic "
            "Construction Risk Intelligence Platform.",
            subtitle_style,
        )
    )

    story.append(
        PageBreak()
    )


    # ========================================================
    # EXECUTIVE SUMMARY
    # ========================================================

    story.append(
        Paragraph(
            "1. Executive Summary",
            heading_style,
        )
    )

    summary_text = (
        summary.get(
            "summary",
            None,
        )
        if isinstance(summary, dict)
        else None
    )

    if summary_text:

        story.append(
            Paragraph(
                str(summary_text),
                normal_style,
            )
        )

    else:

        story.append(
            Paragraph(
                (
                    f"The current assessment indicates an "
                    f"overall risk level of "
                    f"<b>{overall_level}</b> with an "
                    f"overall risk score of "
                    f"<b>{overall_score}/100</b>."
                ),
                normal_style,
            )
        )


    story.append(
        Spacer(
            1,
            10,
        )
    )


    # ========================================================
    # RISK BREAKDOWN
    # ========================================================

    story.append(
        Paragraph(
            "2. Risk Breakdown",
            heading_style,
        )
    )

    risk_data = [
        [
            Paragraph("<b>Risk Area</b>", normal_style),
            Paragraph("<b>Score</b>", normal_style),
            Paragraph("<b>Level</b>", normal_style),
        ],
        [
            "Overall Risk",
            f"{overall_score}/100",
            overall_level,
        ],
        [
            "Site Risk",
            f"{int(site_risk_score)}/100",
            str(
                site_report.get(
                    "site_risk_level",
                    "Unknown",
                )
            ),
        ],
        [
            "Worker Safety Risk",
            f"{int(safety_risk_score)}/100",
            str(
                worker_report.get(
                    "worker_protection_level",
                    "Unknown",
                )
            ),
        ],
        [
            "Insurance Risk",
            f"{int(insurance_score)}/100",
            str(
                insurance_report.get(
                    "insurance_risk_level",
                    "Unknown",
                )
            ),
        ],
    ]

    risk_table = Table(
        risk_data,
        colWidths=[
            70 * mm,
            40 * mm,
            50 * mm,
        ],
    )

    risk_table.setStyle(
        TableStyle(
            [
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.lightgrey,
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(
        risk_table
    )


    # ========================================================
    # SAFETY INTELLIGENCE
    # ========================================================

    story.append(
        Paragraph(
            "3. Worker Safety Intelligence",
            heading_style,
        )
    )

    safety_data = [
        [
            "Workers Detected",
            str(
                worker_report.get(
                    "workers_detected",
                    0,
                )
            ),
        ],
        [
            "Protection Level",
            str(
                worker_report.get(
                    "worker_protection_level",
                    "Unknown",
                )
            ),
        ],
        [
            "Protection Score",
            f"{int(safety_protection_score)}/100",
        ],
        [
            "Confirmed Violations",
            str(
                len(
                    worker_report.get(
                        "confirmed_violations",
                        [],
                    )
                )
            ),
        ],
    ]

    safety_table = Table(
        safety_data,
        colWidths=[
            70 * mm,
            90 * mm,
        ],
    )

    safety_table.setStyle(
        TableStyle(
            [
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(
        safety_table
    )


    # ========================================================
    # PPE VIOLATIONS
    # ========================================================

    violations = worker_report.get(
        "confirmed_violations",
        [],
    )

    if violations:

        story.append(
            Spacer(
                1,
                8,
            )
        )

        story.append(
            Paragraph(
                "<b>Confirmed PPE Violations</b>",
                normal_style,
            )
        )

        for violation in violations:

            story.append(
                Paragraph(
                    f"• {violation}",
                    normal_style,
                )
            )


    # ========================================================
    # SITE HAZARDS
    # ========================================================

    story.append(
        Paragraph(
            "4. Site Hazards",
            heading_style,
        )
    )

    hazards = site_report.get(
        "hazards",
        [],
    )

    if hazards:

        for hazard in hazards:

            story.append(
                Paragraph(
                    f"• {hazard}",
                    normal_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No site hazards were identified.",
                normal_style,
            )
        )


    # ========================================================
    # EQUIPMENT & WEATHER
    # ========================================================

    story.append(
        Paragraph(
            "5. Equipment & Weather Intelligence",
            heading_style,
        )
    )

    operational_data = [
        [
            "Weather Prediction",
            str(weather),
        ],
        [
            "Equipment MTTF",
            str(
                equipment_mttf
            ),
        ],
    ]

    operational_table = Table(
        operational_data,
        colWidths=[
            70 * mm,
            90 * mm,
        ],
    )

    operational_table.setStyle(
        TableStyle(
            [
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(
        operational_table
    )


    # ========================================================
    # COMPLIANCE
    # ========================================================

    story.append(
        Paragraph(
            "6. Compliance Intelligence",
            heading_style,
        )
    )

    compliance_status = compliance_report.get(
        "compliance_status",
        "Unknown",
    )

    compliance_score = compliance_report.get(
        "compliance_score",
        0,
    )

    story.append(
        Paragraph(
            (
                f"<b>Status:</b> {compliance_status}<br/>"
                f"<b>Compliance Score:</b> "
                f"{compliance_score}/100"
            ),
            normal_style,
        )
    )


    compliance_findings = compliance_report.get(
        "findings",
        [],
    )

    if compliance_findings:

        story.append(
            Spacer(
                1,
                8,
            )
        )

        story.append(
            Paragraph(
                "<b>Compliance Findings</b>",
                normal_style,
            )
        )

        for finding in compliance_findings:

            violation = finding.get(
                "violation",
                "Unknown",
            )

            severity = finding.get(
                "severity",
                "Unknown",
            )

            requirement = finding.get(
                "requirement",
                "",
            )

            story.append(
                Paragraph(
                    (
                        f"• <b>{violation}</b> "
                        f"({severity}) — "
                        f"{requirement}"
                    ),
                    normal_style,
                )
            )


    # ========================================================
    # INSURANCE
    # ========================================================

    story.append(
        Paragraph(
            "7. Insurance Intelligence",
            heading_style,
        )
    )

    insurance_level = insurance_report.get(
        "insurance_risk_level",
        "Unknown",
    )

    insurance_recommendation = insurance_report.get(
        "recommendation",
        "No recommendation available.",
    )

    story.append(
        Paragraph(
            (
                f"<b>Risk Level:</b> {insurance_level}<br/>"
                f"<b>Risk Score:</b> "
                f"{int(insurance_score)}/100<br/><br/>"
                f"<b>Recommendation:</b> "
                f"{insurance_recommendation}"
            ),
            normal_style,
        )
    )


    # ========================================================
    # RECOMMENDATIONS
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "8. Recommended Actions",
            heading_style,
        )
    )


    if recommendations:

        recommendation_data = [
            [
                Paragraph(
                    "<b>Category</b>",
                    small_style,
                ),
                Paragraph(
                    "<b>Priority</b>",
                    small_style,
                ),
                Paragraph(
                    "<b>Recommended Action</b>",
                    small_style,
                ),
            ]
        ]


        for recommendation in recommendations:

            category = recommendation.get(
                "category",
                "General",
            )

            priority = recommendation.get(
                "priority",
                "Low",
            )

            action = recommendation.get(
                "action",
                "",
            )

            recommendation_data.append(
                [
                    Paragraph(
                        str(category),
                        small_style,
                    ),
                    Paragraph(
                        str(priority),
                        small_style,
                    ),
                    Paragraph(
                        str(action),
                        small_style,
                    ),
                ]
            )


        recommendation_table = Table(
            recommendation_data,
            colWidths=[
                35 * mm,
                30 * mm,
                95 * mm,
                ],
                repeatRows=1,
            )


        recommendation_table.setStyle(
            TableStyle(
                [
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.5,
                        colors.grey,
                    ),
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.lightgrey,
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "TOP",
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                ]
            )
        )

        story.append(
            recommendation_table
        )

    else:

        story.append(
            Paragraph(
                "No additional recommendations were generated.",
                normal_style,
            )
        )


    # ========================================================
    # FINAL DISCLAIMER
    # ========================================================

    story.append(
        Spacer(
            1,
            20,
        )
    )

    story.append(
        Paragraph(
            "<b>Important:</b> ConstructAI provides "
            "AI-generated risk intelligence to support "
            "construction management and safety decisions. "
            "The insurance indicator is an internal "
            "risk-support metric and is not an insurance "
            "quote, policy decision, legal determination, "
            "or professional engineering judgment.",
            small_style,
        )
    )


    # ========================================================
    # BUILD PDF
    # ========================================================

    document.build(
        story
    )

    buffer.seek(0)

    return buffer